Rails.application.routes.draw do
  get "home/index", to: "home#index"
  resources :tags
  devise_for :users
  resources :categories
  root "home#index"
  resources :posts #RESTful routing - generated by scafffold magic
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
